# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: 1106.org
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: '&copy; 2018 www.1106.org'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: 与qq同步
    url: https://twitter.com/SBootstrap
  - title: 863283750
    url: tencent://AddContact/?fromId=50&fromSubId=1&subcmd=all&uin=863283750
