# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: 1106.org
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2018 www.1106.org'
credits: '<感谢a href="http://startbootstrap.com/">Start Bootstrap</a>; <a href="https://pages.github.com/">GitHub Pages</a>; <a href="https://jekyllrb.com/">Jekyll</a>.提供网页支持'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: qq
    url: http://wpa.qq.com/msgrd?v=3&uin=863283750&site=qq&menu=yes&src_type=web
  - title: 微信
    url: https://www.1106.org/img/weixin.png
  - title: 邮件
    url: https://www.1106.org/addpages/email.html
