# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.1106.org
title: XX劳务派遣公司
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: '&copy; 2018 XX劳务派遣公司 版权所有'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: 扫描二维码，添加微信
    url: https://www.1106.org/img/weixin.png
  - title: 电话 155-2720-8385